YazılımYapımıDönemProjesi/Controllers/ÖğretmenController.cs
using BusinessLayer.Concreate;
using DataAccsessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace YazılımYapımıDönemProjesi.Controllers
{
    
    public class ÖğretmenController : Controller
    {
        // GET: Öğretmen
        QuestionManager questionManager = new QuestionManager(new EfQuestionDal());
        WrongAnswerManager wrongAnswerManager = new WrongAnswerManager(new EfWrongAnswerDal());
        Question_WrongAnswer question_WrongAnswer = new Question_WrongAnswer();

        //Öğretmenin ekledği bütün sorular karrşısında gözükür sayfalanmış bir şekilde
        public ActionResult Index(int p=1)
        {
            var butunSorularınSayfalanması = questionManager.GetAll().ToPagedList(p, 10);
            return View(butunSorularınSayfalanması);
        }
        
        //Öğretmenin soru eklmediği bölüm
        [HttpGet]
        public ActionResult SoruEkle()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SoruEkle(Question question)
        {
            questionManager.Add(question);
            Thread.Sleep(2100);
            return RedirectToAction("Index");
        }

        //Öğretmenin yanlış cevap eklemesi
        [HttpGet]
        public ActionResult YanlisCevapEkle(int id)
        {
            ViewBag.deger = id;
            return View();
        }
        [HttpPost]
        public ActionResult YanlisCevapEkle(WrongAnswer wrongAnswer)
        {
            wrongAnswerManager.Add(wrongAnswer);
            Thread.Sleep(2100);
            return RedirectToAction("Index");
        }

        //öğretmenin eklediği soruyu kendisine gösterilmesi
        public ActionResult EklenenSorununGorunumu(int id)
        {
            question_WrongAnswer.Question = questionManager.GetByLastID(id);
            question_WrongAnswer.WrongAnswer = wrongAnswerManager.GetAll();
            return View(question_WrongAnswer);
        }

        //Eklenen soruları guncelleme sayfasına getirmesi
        public ActionResult SorularıGetir(int id)
        {
            var soruIcerigi = questionManager.GetByQuestionID(id);
            return View("SorularıGetir", soruIcerigi);
        }

        //getirilen soruların güncellenmesi
        [ValidateInput(false)]
        public ActionResult EklenenSorulariGuncelle(Question question)
        {
            questionManager.Update(question);
            Thread.Sleep(2100);
            return RedirectToAction("Index");
        }
    }
}

YazılımYapımıDönemProjesi/Views/Öğretmen/EklenenSorununGorunumu.cshtml
@model EntityLayer.Concrete.Question_WrongAnswer
@{
    ViewBag.Title = "EklenenSorununGorunumu";
    Layout = "~/Views/Shared/_ÖğretmenLayout.cshtml";
}

<br />
<h2 class="space" style="margin:0;margin-top:0px!important;width:100%;">Eklenen Sorunun Görüntüsü</h2>
<section id="page-details">

    @foreach (var x in Model.Question)
    {
        <div class="space">
            <h4><b>Ders Adı:</b> @x.CourseName  -  <b>Ünite Adı:</b> @x.UnitName </h4>
        </div>

        <div class="container space">

            @*soru gövdesinin gösterilmesi*@
            <div>
                <br />
                @Html.Raw(x.QuestionText)
                <br />
            </div>

        </div>
        <div class="space-all">
            @x.CorrectAnswer
        </div>

        //yanlış şıkların gösterilmesi
        foreach (var y in Model.WrongAnswer)
        {
            if (y.QuestionID == x.ID)
            {
                <div class="space-all">
                    @y.WrongAnswer_1
                </div>
                <div class="space-all">
                    @y.WrongAnswer_2
                </div>
                <div class="space-all">
                    @y.WrongAnswer_3
                </div>
            }
        }
    }
</section>
<br />
<br />
<br />

YazılımYapımıDönemProjesi/Views/Öğretmen/Index.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Question>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ÖğretmenLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-3">
                <div class="col-sm-6">
                    <h1>Eklenen Soruların Detayları</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Sorular Tablosu</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 10%">
                                Course Name
                            </th>
                            <th style="width: 10%">
                                Unit Name
                            </th>
                            <th style="width: 37%">
                                QuestionText
                            </th>
                            <th style="width: 9%">
                                Correct Answer
                            </th>
                            <th style="width: 17%">
                                Wrong Answer
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.ID
                                </td>
                                <td>
                                    <a>
                                        @item.CourseName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.AddDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <span>@item.UnitName</span>
                                </td>
                                <td>
                                    <smal>@item.QuestionText.Substring(0, item.QuestionText.Length - (item.QuestionText.Length / 3 + item.QuestionText.Length / 3 + item.QuestionText.Length / 4))...</smal>
                                </td>
                                <td>
                                    <span>@item.CorrectAnswer.Substring(0, item.CorrectAnswer.Length - (item.CorrectAnswer.Length / 3 + item.CorrectAnswer.Length / 6))...</span>
                                </td>
                                <td class="project-actions">
                                    <a class="btn btn-primary btn-sm mt-1" href="/Öğretmen/EklenenSorununGorunumu/@item.ID">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerik
                                    </a>
                                    <a class="btn btn-info btn-sm mt-1" href="/Öğretmen/SorularıGetir/@item.ID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-warning btn-sm mt-1" href="/Öğretmen/YanlisCevapEkle/@item.ID">
                                        Yanlış Cevap Ekle
                                    </a>

                                </td>
                            </tr>
                        }
                    </tbody>
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 10%">
                                Course Name
                            </th>
                            <th style="width: 10%">
                                Unit Name
                            </th>
                            <th style="width: 37%">
                                QuestionText
                            </th>
                            <th style="width: 9%">
                                Correct Answer
                            </th>
                            <th style="width: 17%">
                                Wrong Answer
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

<a href="/Öğretmen/SoruEkle/" class="btn btn-primary">Yeni Soru Ekle</a>

@*sayfalama işleminin gerçekleştirilmesi*@
<span style="text-align:center; position:relative;">@Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p })) </span>




<br />
<br />
<br />

YazılımYapımıDönemProjesi/Views/Öğretmen/SoruEkle.cshtml
@model EntityLayer.Concrete.Question
@{
    ViewBag.Title = "SoruEkle";
    Layout = "~/Views/Shared/_ÖğretmenLayout.cshtml";
}
@section Scripts{
    <script>
        var editor = CKEDITOR.replace('txtContent', {
            customConfig: '~/Scripts/ckeditor/ckeditor.js'
        });
    </script>
}
<br />
<h2>Yeni Soru Ekle</h2>
<br />
@*yeni soruların öğretmen tarafından eklenilmesi*@
<form class="form-group col-md-11  " method="post">
    @Html.LabelFor(x => x.CourseName)
    @Html.TextBoxFor(x => x.CourseName, new { @required = "required", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.UnitName)
    @Html.TextBoxFor(x => x.UnitName, new { @required = "required", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SubjectName)
    @Html.TextBoxFor(x => x.SubjectName, new { @required = "required", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.QuestionText)
    @Html.TextAreaFor(x => x.QuestionText, new { htmlAttributes = new { @required = "required", @class = "form-control" } , id = "txtContent" })
    <br />    
    @Html.LabelFor(x => x.CorrectAnswer)
    @Html.TextBoxFor(x => x.CorrectAnswer, new { @required = "required", @class = "form-control" })
    <br />    
    <button onclick="validation();" class="btn btn-primary">Soru Ekle</button>
</form>

<script type="text/javascript">
    demo();
    function validation() {
        swal("Succsess!", "Sorunuzu Başarıyla Eklediniz", "success", {
            button: null,
        });
    }

</script>

YazılımYapımıDönemProjesi/Views/Öğretmen/SorularıGetir.cshtml
@model EntityLayer.Concrete.Question
@{
    ViewBag.Title = "SorularıGetir";
    Layout = "~/Views/Shared/_ÖğretmenLayout.cshtml";
}

@section Scripts{
    <script>
        var editor = CKEDITOR.replace('txtContent', {
            customConfig: '~/Scripts/ckeditor/ckeditor.js'
        });
    </script>
}

@*öğretmenin yaptığı hatayı daha sonra düzeltmesi için güncelleme sayfası*@
@using (Html.BeginForm("EklenenSorulariGuncelle", "Öğretmen", FormMethod.Post))
{
<form class="form-group col-md-11">
    @Html.TextBoxFor(x => x.ID, new { style = "display:none;", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CourseName)
    @Html.TextBoxFor(x => x.CourseName, new { @required = "required", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.UnitName)
    @Html.TextBoxFor(x => x.UnitName, new { @required = "required", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.QuestionText)
    @Html.TextAreaFor(x => x.QuestionText, new { htmlAttributes = new { @required = "required", @class = "form-control" }, id = "txtContent" })
    <br />
    @Html.LabelFor(x => x.CorrectAnswer)
    @Html.TextBoxFor(x => x.CorrectAnswer, new { @required = "required", @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.AddDate, new { style = "display:none;", @required = "required", @class = "form-control" })
    <br />
    <div>
        <button onclick="validation();" class="btn btn-warning">Güncelle</button>
    </div>
</form>
}

<script type="text/javascript">
    demo();
    function validation() {
        swal("Succsess!", "Sorunuzu Başarıyla Güncellediniz", "success", {
            button: null,
        });
    }

</script>

YazılımYapımıDönemProjesi/Views/Öğretmen/YanlisCevapEkle.cshtml
@model EntityLayer.Concrete.WrongAnswer
@{
    ViewBag.Title = "YanlisCevapEkle";
    Layout = "~/Views/Shared/_ÖğretmenLayout.cshtml";
}

<div class="container">
    <div class="row">

        <div class="col-md-10">
            <br />
            <h2>Yanlış Cevap Ekle</h2>
            <br />
            <div class="content-from">
                <form class="form-group" method="post">
                    @Html.TextBoxFor(x => x.QuestionID, new { style = "display:none;", @Value = ViewBag.deger })
                    <label>Yanlış Cevap 1</label>
                    @Html.TextBoxFor(x => x.WrongAnswer_1, new { @required = "required", @class = "form-control " })
                    <br />
                    <label>Yanlış Cevap 2</label>
                    @Html.TextBoxFor(x => x.WrongAnswer_2, new { @required = "required", @class = "form-control" })
                    <br />
                    <label>Yanlış Cevap 3</label>
                    @Html.TextBoxFor(x => x.WrongAnswer_3, new { @required = "required", @class = "form-control" })
                    <br />

                    <button onclick="validation();" class="btn btn-primary">Yanlış Cevapları Ekle</button>


                </form>
            </div>
        </div>
        <div class="col-md-6">

        </div>
    </div>
</div>

<script type="text/javascript">
    demo();
    function validation() {
        swal("Succsess!", "Yanlış Şıkları Başarıyla Eklediniz", "success", {
            button: null,
        });
    }

</script>